// SIGN UP
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
// SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";
// SIGN OUT
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
// RESET PASSWORD
export const RESET_SUCCESS = "RESET_SUCCESS"
export const RESET_ERROR = "RESET_ERROR"
// POST
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_ERROR = "CREATE_POST_ERROR"